services:
  - type: web
    name: thermacity-backend
    env: docker
    region: singapore # Closest to India
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres.ctjbapfdnyioazajfasp:ThermaCity123@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - key: CORS_ORIGINS
        value: https://frontend-jet-tau-47.vercel.app,https://admin-frontend-chi-weld.vercel.app
      - key: ML_MODEL_PATH
        value: /app/ml/models/rf_lst_predictor_v1.joblib
      - key: DEBUG
        value: "false"
